export enum RecommendationCategory {
  DIAGNOSTIC = 'DIAGNOSTIC',
  CONSULTATION = 'CONSULTATION',
  TREATMENT = 'TREATMENT',
  PREVENTIVE = 'PREVENTIVE',
  LIFESTYLE = 'LIFESTYLE',
  OTHER = 'OTHER',
}