export enum RecommendationServiceType {
  LAB_TEST = 'LAB_TEST',
  RADIOLOGY = 'RADIOLOGY',
  SPECIALIST = 'SPECIALIST',
  VACCINATION = 'VACCINATION',
  PHYSIOTHERAPY = 'PHYSIOTHERAPY',
  DIETICIAN = 'DIETICIAN',
  MENTAL_HEALTH = 'MENTAL_HEALTH',
  PROCEDURE = 'PROCEDURE',
  CERTIFICATE = 'CERTIFICATE',
  CUSTOM = 'CUSTOM',
}