import {
  Injectable,
  NotFoundException,
  BadRequestException,
} from '@nestjs/common';

import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

import { Prescription } from './prescription.entity';
import { CreatePrescriptionDto } from './dto/create-prescription.dto';

import {
  Appointment,
  AppointmentStatus,
} from '../appointment/appointment.entity';

import PDFDocument from 'pdfkit';
import { Response } from 'express';
import { MailService } from '../mail/mail.service';

@Injectable()
export class PrescriptionService {
  constructor(
  @InjectRepository(Prescription)
  private prescriptionRepo: Repository<Prescription>,

  @InjectRepository(Appointment)
  private appointmentRepo: Repository<Appointment>,

  private readonly mailService: MailService,
) {}

  async createPrescription(dto: CreatePrescriptionDto) {
    const appointment = await this.appointmentRepo.findOne({
      where: {
        id: dto.appointmentId,
      },
      relations: {
        doctor: {
          hospital: true,
        },
        patient: true,
        slot: true,
      },
    });

    if (!appointment) {
      throw new NotFoundException('Appointment not found');
    }

    if (appointment.status !== AppointmentStatus.COMPLETED) {
      throw new BadRequestException(
        'Prescription can be added only after appointment is completed',
      );
    }

    if (!appointment.patient) {
      throw new BadRequestException(
        'Appointment is not linked with patient',
      );
    }

    const existingPrescription =
      await this.prescriptionRepo.findOne({
        where: {
          appointment: {
            id: dto.appointmentId,
          },
        },
      });

    if (existingPrescription) {
      throw new BadRequestException(
        'Prescription already exists for this appointment',
      );
    }

    const prescription = this.prescriptionRepo.create({
      appointment,
      doctor: appointment.doctor,
      patient: appointment.patient,
      diagnosis: dto.diagnosis,
      medicines: dto.medicines,
      notes: dto.notes,
    });

    const savedPrescription =
  await this.prescriptionRepo.save(prescription);

try {
  await this.mailService.sendPrescriptionReady({
    to: appointment.patient.email,
    patientName: appointment.patient.fullName,
    doctorName: appointment.doctor.doctorName,
  });
} catch (error) {
  console.error('Prescription email failed:', error);
}

return savedPrescription;
  }

  async getAllPrescriptions() {
    return this.prescriptionRepo.find({
      relations: {
        appointment: true,
        doctor: {
          hospital: true,
        },
        patient: true,
      },
      order: {
        id: 'DESC',
      },
    });
  }

  async getMyPrescriptions(patientId: string) {
    return this.prescriptionRepo.find({
      where: {
        patient: {
          id: patientId,
        },
      },
      relations: {
        appointment: true,
        doctor: {
          hospital: true,
        },
        patient: true,
      },
      order: {
        id: 'DESC',
      },
    });
  }

  async getByAppointment(appointmentId: number) {
    return this.prescriptionRepo.findOne({
      where: {
        appointment: {
          id: appointmentId,
        },
      },
      relations: {
        appointment: true,
        doctor: {
          hospital: true,
        },
        patient: true,
      },
    });
  }

  async generatePdf(id: number, res: Response) {
    const prescription = await this.prescriptionRepo.findOne({
      where: {
        id,
      },
      relations: {
        appointment: {
          slot: true,
        },
        doctor: {
          hospital: true,
        },
        patient: true,
      },
    });

    if (!prescription) {
      throw new NotFoundException('Prescription not found');
    }

    const hospitalName =
      prescription.doctor?.hospital?.hospitalName ||
      'MediCare Hospital';

    const appointmentDate =
      prescription.appointment?.slot?.date || '-';

    const appointmentTime = prescription.appointment?.slot
      ? `${prescription.appointment.slot.startTime} - ${prescription.appointment.slot.endTime}`
      : '-';

    const doc = new PDFDocument({
      margin: 50,
    });

    res.setHeader('Content-Type', 'application/pdf');

    res.setHeader(
      'Content-Disposition',
      `attachment; filename=prescription-${id}.pdf`,
    );

    doc.pipe(res);

    doc
      .fontSize(24)
      .text(hospitalName.toUpperCase(), {
        align: 'center',
      });

    doc
      .fontSize(11)
      .text('Digital Medical Prescription', {
        align: 'center',
      });

    doc.moveDown(1);

    doc
      .fontSize(10)
      .text(
        'Generated by MediCare Smart Healthcare Platform',
        {
          align: 'center',
        },
      );

    doc.moveDown(2);

    doc.fontSize(12).text(`Prescription ID: ${prescription.id}`);

    doc.text(
      `Generated Date: ${new Date(
        prescription.createdAt,
      ).toLocaleDateString()}`,
    );

    doc.text(`Appointment Date: ${appointmentDate}`);
    doc.text(`Appointment Time: ${appointmentTime}`);

    doc.moveDown();

    doc.fontSize(15).text('Patient Details', {
      underline: true,
    });

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .text(
        `Patient: ${prescription.patient?.fullName || '-'}`,
      );

    doc.text(`Mobile: ${prescription.patient?.mobile || '-'}`);

    doc.text(`Email: ${prescription.patient?.email || '-'}`);

    doc.moveDown();

    doc.fontSize(15).text('Doctor Details', {
      underline: true,
    });

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .text(
        `Doctor: ${
          prescription.doctor?.doctorName || '-'
        }`,
      );

    doc.text(
      `Specialization: ${
        prescription.doctor?.specialization || '-'
      }`,
    );

    doc.text(
      `Qualification: ${
        prescription.doctor?.qualification || '-'
      }`,
    );

    doc.moveDown();

    doc.fontSize(15).text('Diagnosis', {
      underline: true,
    });

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .text(prescription.diagnosis || '-');

    doc.moveDown();

    doc.fontSize(15).text('Medicines', {
      underline: true,
    });

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .text(prescription.medicines || '-');

    doc.moveDown();

    doc.fontSize(15).text('Notes', {
      underline: true,
    });

    doc.moveDown(0.5);

    doc.fontSize(12).text(prescription.notes || '-');

    doc.moveDown(3);

    doc.text('Doctor Signature: ____________________');

    doc.moveDown(2);

    doc
      .fontSize(9)
      .fillColor('gray')
      .text(
        'This is a digitally generated prescription. Please consult your doctor before changing any medication.',
        {
          align: 'center',
        },
      );

    doc.end();
  }
}